version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: 'always'
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    # cap_add:
    #   - SYS_NICE
    networks:
      - schedule

  backend:
    container_name: backend
    build: ./api
    ports:
      - 9393:9393
    platform: linux/x86_64
    working_dir: /api
    # command: sh -c "echo "foi" && npm run migrate"
    volumes:
      - ./api:/api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - schedule

networks:
  schedule:
    driver: bridge
