version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: 'always'
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    # cap_add:
    #   - SYS_NICE
    networks:
      - agende

  # app:
  #   container_name: agende-me
  #   build: ./agende_me
  #   # image: node:18
  #   platform: linux/x86_64
  #   working_dir: /app
  #   command: sh -c "npm install && npm run android && npm start"
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./agende_me:/app
  #   networks:
  #     - agende
  #   depends_on:
  #     - db
  #     - backend

  backend:
    container_name: backend
    build: ./api
    ports:
      - 9393:9393
    platform: linux/x86_64
    restart: 'always'
    working_dir: /api
    tty: true
    # command: sh -c "echo "foi" && npm run migrate"
    volumes:
      - ./api:/api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - agende

  redis:
    image: redis:latest
    container_name: redis
    restart: 'always'
    ports:
      - "6379:6379"
    networks:
      - agende
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  agende:
    driver: bridge
