version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
